### ISSUE TITLE
try_inplace_array always allocates 4096 entries on the stack

### ISSUE THREAD

**Issue by kvark** [NotIntMan/inplace_it#4]
We are looking through the `inplace` code in search for explanation to https://github.com/gfx-rs/gfx/issues/3319.

It appears to me that `try_inplace_array` doesn't do what you expect it to. Since it's a function, and one of the match arms has basically `[T; 4096]`, the compiler has to consider this a part of the stack allocation for the function, unconditionally. You can see this in the [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=da5f43113af6087f68ee29d24d23f545):
```
playground::foo:
	movl	$4376, %eax // I think this is our stack size
	callq	__rust_probestack
	subq	%rax, %rsp
	movq	%rdi, 4344(%rsp)
	movb	$0, 4343(%rsp)
	movb	$1, 4343(%rsp)
	movq	%rdi, %rax
	subq	$1, %rax
	movq	%rdi, 16(%rsp)
	je	.LBB80_3
	jmp	.LBB80_16
```

So, in terms of stack allocation, the current implementation is equivalent to this:
```rust
pub fn try_inplace_array<T, R, Consumer>(size: usize, consumer: Consumer) -> Result<R, Consumer>
    where Consumer: FnOnce(UninitializedSliceMemoryGuard<T>) -> R
{
            let mut memory: [MaybeUninit<T>; 4096] = unsafe { MaybeUninit::uninit().assume_init() };
            unsafe {
                consumer(UninitializedSliceMemoryGuard::new(&mut memory[..size]))
            }
}
```

**Comment by NotIntMan** [comment]
@kvark, thanks for your feedback. I did some investigation but this quite tricky to validate stack memory consumption. I will publish little fix in few days but not sure it will help.

**Comment by NotIntMan** [comment]
@kvark, you can view the fix I am about to publish in the issue related commit. Maybe there are comments or suggestions. I'll think about it until tomorrow (still, it's Friday night and I'm tired).

**Comment by kvark** [comment]
Looks great! This is close to what I wanted to suggest, but better :)

**Comment by NotIntMan** [comment]
I published a fix and now closing the issue. Feel free to reopen it if that not helps.
