### ISSUE TITLE
Better glue for general iterators

### ISSUE THREAD

**Issue by kvark** [NotIntMan/inplace_it#5]
A typical use case we have is: there is an iterator, and we want to produce something from it (via `map`) and obtain a slice of the result on the stack (preferably). We used to have `ExactSizeIterator`, which we can get `len()` to pass into `inplace_it`. However, a question was raised by @zakarumych about whether we could just use the regular `size_hint()` on the iterator instead. The hint may be unbound, which I think would work very well for `inplace_it`, since it has an upper bound of what it can allocate on the stack, anyway.

So we could do something like this today:
```rust
inplace_or_alloc_array(iterator.size_hint().1.unwrap_or(!0), |uninit_guard| {
            let values = uninit_guard.init_with_iter(iterator);
            ...
})
```
This seems hacky for passing `!0` into your library just to tell it we don't have an upper bound. It's also more verbose than it has to be. If there was a tighter integration of `Iterator` into this library, the routine could look like this:
```rust
inplace_iter(iterator, |values| {
            ...
})
```
This would be perfect for us

**Comment by kvark** [comment]
Actually, no, we can't have that workaround since `init_with_iter` requires the `ExactSizeIterator`. So changes in `inplace_it` are needed here!

**Comment by zakarumych** [comment]
For unbound iter with non-zero-sized elements this

```
inplace_or_alloc_array(iterator.size_hint().1.unwrap_or(!0), |uninit_guard| {
            let values = uninit_guard.init_with_iter(iterator);
            ...
})
```

will result in `Vec::with_capacity(!0)` call. Which in turn will `panic!("capacity overflow");`

**Comment by kvark** [comment]
Ok, so it looks like we don't have a proper workaround here. @NotIntMan would you be interested in trying to get that function exposed? Or would you want a PR by us?

**Comment by NotIntMan** [comment]
@kvark, @zakarumych, it looks interesting. As I understand it, you need the following:
- Function signature is
```rust
fn inplace_or_alloc_from_iter<Iter, R, Consumer>(iter: Iter, consumer: Consumer) -> R
where
    Iter: IntoIterator,
    Consumer: FnOnce(UninitializedSliceMemoryGuard<Iter::Item>) -> R,
```
- Behaviour is
```rust
if let Some(upper_bound_hint) = iter.size_hint().1 {
    // calling inplace_or_alloc_array with size = upper_bound_hint and initializing memory from iterator
} else {
    // calling alloc_array with size = upper_bound_hint and initializing memory from iterator
}
```

Please, correct me if I wrong.

Answering your question, I'm interested in. But I will have time to start doing this in next sunday only. It's in three days from today if my excellent English got you confused. Will you wait for it?

**Comment by NotIntMan** [comment]
I also realized that this feature may require some breaking changes because of function `SliceMemoryGuard::new` which is encapsulates memory initialization. Hope you're not use it directly:)

**Comment by kvark** [comment]
@NotIntMan 
Thank you for the responses! It's up to you whether this needs to include breaking changes. As an outsider, it doesn't seem to me that you have to break anything. I.e. you can add another constructor alongside `SliceMemoryGuard::new` to avoid touching it.

> // calling inplace_or_alloc_array with size = upper_bound_hint and initializing memory from iterator

The important note here is that "initializing memory from iterator" would work differently from `init_with_iter`. it would accept the fact that there may be less items than the user requested (but not more, obviously).

> // calling alloc_array with size = upper_bound_hint and initializing memory from iterator

Note that we don't have an upper bound hint in this case, so we'd expect you to just `collect()` the iterator.
There could be a discussion about supporting different containers from `Vec` in a generic way, e.g. something bound by `C: FromIterator<I::Item> + Borrow<[I::Item]>`, but in reality we don't need this in the near future.

> It's in three days from today if my excellent English got you confused. Will you wait for it?

We'll need that as soon as possible, but without rushing you. In the worst case, we'll release gfx-0.7 without taking advantage of this change. So don't feel too pressured, please :)

**Comment by NotIntMan** [comment]
> Note that we don't have an upper bound hint in this case, so we'd expect you to just collect() the iterator.

Okay. I got your point. In that case, function signature will simplify to:
```rust
fn inplace_or_alloc_from_iter<Iter, R, Consumer>(iter: Iter, consumer: Consumer) -> R
where
    Iter: IntoIterator,
    Consumer: FnOnce(&[Iter::Item]) -> R,
```

> There could be a discussion about supporting different containers from Vec in a generic way, e.g. something bound by C: FromIterator<I::Item> + Borrow<[I::Item]>, but in reality we don't need this in the near future.

That's huge. It would be better to open a separated discussion if you really need it someday.

**Comment by zakarumych** [comment]
I think user may want to modify content of the slice, so `Consumer: FnOnce(&mut [Iter::Item]) -> R` would be nice.

**Comment by kvark** [comment]
@NotIntMan are you still planning to give it a go tomorrow? Let us know if it changes :)

**Comment by NotIntMan** [comment]
@kvark, it's okay:) Already working on it.

**Comment by NotIntMan** [comment]
@kvark, @zakarumych, https://github.com/NotIntMan/inplace_it/pull/6

**Comment by kvark** [comment]
Great, thank you!
Looking forward to see this on crates :)

**Comment by NotIntMan** [comment]
`0.3.3` was nicely released
